import Head from 'next/head'
import Feed from '../components/Feed'
import Sidebar from '../components/Sidebar'
import Widgets from '../components/Widgets'

export default function Home({news, randomUserData}) {
  return (
    <div>
      <Head>
        <title>Twitter clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex flex-row min-h-screen mx-auto'>
        {/* Sidebar */}
        <Sidebar />
        {/* Feed section */}
        <Feed />
        {/* Widgets */}
        <Widgets news={news.articles} randomUser={randomUserData}/>

        {/* Modal */}
      </main>
    </div>
  )
}

// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json

export async function getServerSideProps() {
  const newsResult = await fetch('https://saurav.tech/NewsAPI/top-headlines/category/business/us.json');
  const news = await newsResult.json();

  const randomUser = await fetch("https://randomuser.me/api/?results=50&inc=name,login,picture").then((res) => res.json());
  const randomUserData = randomUser.results;

  return {
    props: {
      news,
      randomUserData
    }
  };
}