import Head from 'next/head'
import Feed from '../components/Feed'
import Sidebar from '../components/Sidebar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex flex-row min-h-screen max-w-7xl mx-auto'>
        {/* Sidebar */}
        <Sidebar />
        {/* Feed section */}
        <Feed />
        {/* Widgets */}

        {/* Modal */}
      </main>
    </div>
  )
}
